plugins {
    id 'java'
    id 'com.arc-e-tect.architecture-validator'
}

group = 'com.arc-e-tect.example.libraryrules'
version = '0.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testArchitectureImplementation libs.layer.validator
}

architectureValidator {
    basePackage = 'com.arc_e_tect.example.libraryrules'
    ignoreFailures = true
}