plugins {
    id 'java'
    id 'com.arc-e-tect.architecture-validator'
}

group = 'com.example.libraryrules'
version = '0.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testArchitectureImplementation 'com.org.ea:layer-validator:1.0.0'
}

architectureValidator {
    basePackage = 'com.example.libraryrules'
    ignoreFailures = true
}