plugins {
    id 'java'
    id 'com.arc-e-tect.architecture-validator'
}

group = 'com.arc-e-tect.example.hexapp'
version = '0.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

architectureValidator {
    basePackage = 'com.arc_e_tect.example.hexapp'

    hexagonalArchitecture {
        inPorts = ['..port.in..']
        outPorts = ['..port.out..']
        domainModel = ['..domain..']
        adapters = ['..adapter..']
        inboundAdapters = ['..adapter.in..']
        outboundAdapters = ['..adapter.out..']
        applicationServices = ['..application..']
    }
}
