plugins {
    id 'java-library'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.javaparser.core
    implementation libs.swagger.parser

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
    testRuntimeOnly    libs.junit.platform.launcher
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
        showStandardStreams = true
    }
}
