package com.arc_e_tect.gradle.trackerlens;

import java.time.Duration;
import java.time.Instant;

/**
 * The static (and near-static) file contents {@code bootstrapTrackerLensProject} writes: a minimal
 * lens-pack project and a minimal sample project consuming it, matching {@code LENS_TUTORIAL.adoc}'s
 * own worked example exactly, so following the tutorial and running the task land on the same
 * result.
 *
 * <p>Only {@link #sampleProjectBuildGradle(String)} (the plugin version) and
 * {@link #sampleHistoryNdjson(Instant)} (relative timestamps, so the sample data is never stale)
 * vary; everything else is fixed, illustrative boilerplate the generated project's own README
 * explains how to edit.</p>
 */
final class BootstrapProjectFiles {

    private BootstrapProjectFiles() {}

    static String topLevelReadme() {
        return """
                = Tracker Lens bootstrap project

                Generated by `bootstrapTrackerLensProject`. Two independent Gradle projects, matching the
                tracker-lens plugin's own `LENS_TUTORIAL.adoc` walkthrough:

                `lens-pack/`::
                A minimal style-pack project. Publish it to a local Maven repository, then consume it from `sample-project/`.

                `sample-project/`::
                A minimal project applying the `tracker-lens` plugin, already configured to consume `lens-pack`'s
                lens and render a dashboard from a small bundled sample history file.

                == Try it

                [source,bash]
                ----
                cd lens-pack
                gradle publish

                cd ../sample-project
                gradle generateTrackerLensDashboard
                ----

                Open `sample-project/build/reports/tracker-lens/dashboard.html` and confirm the lens switcher
                includes `my-lens`.

                See the full walkthrough, including how to grow this into a multi-lens pack, in the tracker-lens
                plugin's own `LENS_TUTORIAL.adoc`.
                """;
    }

    static String lensPackSettingsGradle() {
        return "rootProject.name = 'my-tracker-lens-pack'\n";
    }

    static String lensPackBuildGradle() {
        return """
                // Generated by bootstrapTrackerLensProject.
                //
                // Publishes a lens-pack jar: a jar containing one or more lens CSS files under the fixed
                // META-INF/arc-e-tect/tracker-lens/lenses/ resource path - see
                // src/main/resources/META-INF/arc-e-tect/tracker-lens/lenses/my-lens.css in this project.
                //
                // group/artifactId/version below are placeholders. Change them to your own values - and update
                // the matching lensStyle coordinate in ../sample-project/build.gradle to match - before
                // publishing anywhere other than the local build/localMaven used for testing here.
                plugins {
                    id 'java-library'
                    id 'maven-publish'
                }

                group = 'com.example'
                version = '0.1.0'

                publishing {
                    publications {
                        mavenJava(MavenPublication) {
                            from components.java
                            groupId = 'com.example'
                            artifactId = 'my-tracker-lens-pack'
                            version = project.version
                        }
                    }
                    repositories {
                        maven {
                            name = 'localMaven'
                            url = uri(layout.buildDirectory.dir('localMaven'))
                        }
                    }
                }
                """;
    }

    static String lensPackReadme() {
        return """
                = my-tracker-lens-pack

                A minimal Tracker Lens style pack, generated by `bootstrapTrackerLensProject`.

                `src/main/resources/META-INF/arc-e-tect/tracker-lens/lenses/my-lens.css` is the boilerplate lens
                generated for you - open it and start replacing the placeholder colors documented inline.

                Add more lenses by adding more `.css` files in the same directory; no build changes are needed
                for additional lenses.

                == Publish locally

                [source,bash]
                ----
                gradle publish
                ----

                Writes the jar and Maven metadata under `build/localMaven/`, consumed by `../sample-project`.
                """;
    }

    static String sampleProjectSettingsGradle() {
        return "rootProject.name = 'tracker-lens-sample-project'\n";
    }

    static String sampleProjectBuildGradle(String pluginVersion) {
        return """
                // Generated by bootstrapTrackerLensProject.
                //
                // Applies the tracker-lens plugin - pinned to the version that generated this file, %s, so
                // regenerating after upgrading the plugin picks up the new version automatically - and
                // consumes ../lens-pack's lens via the lensStyle configuration.
                plugins {
                    id 'java-library'
                    id 'com.arc-e-tect.tracker-lens' version '%s'
                }

                repositories {
                    mavenLocal()
                    mavenCentral()
                    maven {
                        url = uri('../lens-pack/build/localMaven')
                    }
                }

                trackerLens {
                    trackers {
                        register('bdd-scenarios') {
                            historyFiles.from(file('src/main/resources/gherkin-progress-history.ndjson'))
                            source = com.arc_e_tect.gradle.trackerlens.TrackerSourceKind.GHERKIN_SCENARIO
                        }
                    }
                }

                dependencies {
                    lensStyle 'com.example:my-tracker-lens-pack:0.1.0'
                }
                """.formatted(pluginVersion, pluginVersion);
    }

    static String sampleProjectReadme() {
        return """
                = tracker-lens-sample-project

                A minimal project for testing `../lens-pack`'s lens end-to-end, generated by
                `bootstrapTrackerLensProject`. Comes with a small bundled sample history file so the dashboard
                has something to render immediately, with no other setup.

                == Try it

                Publish the lens pack first:

                [source,bash]
                ----
                cd ../lens-pack
                gradle publish
                ----

                Then generate the dashboard:

                [source,bash]
                ----
                gradle generateTrackerLensDashboard
                ----

                Open `build/reports/tracker-lens/dashboard.html` and confirm the lens switcher includes `my-lens`.
                """;
    }

    static String sampleHistoryNdjson(Instant now) {
        Instant scenario1Listed = now.minus(Duration.ofDays(20));
        Instant scenario1Defined = now.minus(Duration.ofDays(15));
        Instant scenario1Implemented = now.minus(Duration.ofDays(10));
        Instant scenario2Listed = now.minus(Duration.ofDays(12));
        Instant scenario2Defined = now.minus(Duration.ofDays(5));
        Instant scenario3Listed = now.minus(Duration.ofDays(8));

        StringBuilder ndjson = new StringBuilder();
        ndjson.append("{\"fingerprint\":\"sample-1\",\"scenarioName\":\"Place an order\",\"featureTitle\":\"Ordering\",")
                .append("\"listedAt\":\"").append(scenario1Listed).append("\",")
                .append("\"definedAt\":\"").append(scenario1Defined).append("\",")
                .append("\"implementedAt\":\"").append(scenario1Implemented).append("\",")
                .append("\"lastSeenAt\":\"").append(now).append("\",\"removedAt\":null}\n");
        ndjson.append("{\"fingerprint\":\"sample-2\",\"scenarioName\":\"Cancel an order\",\"featureTitle\":\"Ordering\",")
                .append("\"listedAt\":\"").append(scenario2Listed).append("\",")
                .append("\"definedAt\":\"").append(scenario2Defined).append("\",")
                .append("\"implementedAt\":null,")
                .append("\"lastSeenAt\":\"").append(now).append("\",\"removedAt\":null}\n");
        ndjson.append("{\"fingerprint\":\"sample-3\",\"scenarioName\":\"Refund an order\",\"featureTitle\":\"Ordering\",")
                .append("\"listedAt\":\"").append(scenario3Listed).append("\",")
                .append("\"definedAt\":null,\"implementedAt\":null,")
                .append("\"lastSeenAt\":\"").append(now).append("\",\"removedAt\":null}\n");
        return ndjson.toString();
    }
}
