pluginManagement {
    includeBuild('../../../architecture-validator')
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
    id 'de.fayard.refreshVersions' version '0.60.6'
}

refreshVersions {
    rejectVersionIf {
        candidate.stabilityLevel.isLessStableThan(current.stabilityLevel)
    }
}

includeBuild('../../../architecture-validator') {
    dependencySubstitution {
        substitute module('com.arc-e-tect:spring-rules') using project(':spring-rules')
        substitute module('com.arc-e-tect:spring-rules:1.0.0') using project(':spring-rules')
        substitute module('com.arc-e-tect:architecture-validation-spring-rules') using project(':spring-rules')
        substitute module('com.arc-e-tect:architecture-validation-spring-rules:1.0.0') using project(':spring-rules')
    }
}

rootProject.name = 'architecture-validator-single-module-spring'