plugins {
    alias(libs.plugins.tracker.lens)
}

repositories {
    mavenCentral()
}

trackerLens {
    defaultLens = 'ocean-lens'

    trackers {
        register('bdd-scenarios') {
            historyFiles.from(file('gherkin-progress-history.ndjson'))
            source = com.arc_e_tect.gradle.trackerlens.TrackerSourceKind.GHERKIN_SCENARIO
        }
    }
}

dependencies {
    lensStyle libs.geo.tracker.lens.pack
}
