plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.org.ea'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    api libs.archunit.junit5.iff
    compileOnly libs.junit.jupiter.iff
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'layer-validator'
        }
    }
}