= Architecture Validator
:toc: left
:toc-title: Contents
:toclevels: 2
:icons: font
:source-highlighter: rouge

image:https://img.shields.io/badge/Java-21%2B-blue[Java 21+,link=https://adoptium.net]
image:https://img.shields.io/badge/Gradle-9.x-02303A?logo=gradle[Gradle 9.x,link=https://gradle.org]

Architecture Validator in this repository contains the standalone Gradle plugin project.
The companion Spring rule-pack has moved to the SoftwareEngineeringDoneRight-Library repository as `spring-rules`.

== Project

[cols="1,3",options="header"]
|===
|Project |Purpose

|`plugin`
|Core Gradle plugin that generates and runs ArchUnit-based architecture tests and supports external rule packs.
|===

== Build from Repository Root

The plugin is built from its own directory and wrapper.

[source,bash]
----
cd architecture-validator/plugin
./gradlew build
----

== Documentation

link:plugin/README.adoc[Plugin README]

The Spring Rules project now lives in the SoftwareEngineeringDoneRight-Library repository.

== Included Guides

include::plugin/README.adoc[leveloffset=+1]

== License

This project is part of the _Software Engineering Done Right_ repository.
See link:../LICENSE[LICENSE] for details.