= Architecture Validator
:toc: left
:toc-title: Contents
:toclevels: 2
:icons: font
:source-highlighter: rouge

image:https://img.shields.io/badge/Java-21%2B-blue[Java 21+,link=https://adoptium.net]
image:https://img.shields.io/badge/Gradle-9.x-02303A?logo=gradle[Gradle 9.x,link=https://gradle.org]

Architecture Validator is split into two standalone Gradle projects.
Both projects use their own Gradle wrapper, semantic-release configuration, and GitHub workflows.

== Project Split

[cols="1,3",options="header"]
|===
|Project |Purpose

|`plugin`
|Core Gradle plugin that generates and runs ArchUnit-based architecture tests and supports external rule packs.

|`spring-rules`
|Companion Spring rule-pack artifact consumed through `testArchitectureImplementation`.
|===

== Build from Repository Root

Each project is built from its own directory and its own wrapper.

[source,bash]
----
cd architecture-validator/plugin
./gradlew build

cd ../spring-rules
./gradlew build
----

== Documentation

link:plugin/README.adoc[Plugin README]

link:spring-rules/README.adoc[Spring Rules README]

== Included Guides

include::plugin/README.adoc[leveloffset=+1]

include::spring-rules/README.adoc[leveloffset=+1]

== License

This project is part of the _Software Engineering Done Right_ repository.
See link:../LICENSE[LICENSE] for details.