plugins {
    id 'java-library'
    id 'maven-publish'
}

group = rootProject.group
version = rootProject.version

base {
    archivesName = 'architecture-validator-spring-rules'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withJavadocJar()
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    api libs.archunit.junit5.iff
    compileOnly libs.spring.context.iff
    compileOnly libs.junit.jupiter.iff

    testImplementation libs.junit.jupiter.iff
    testRuntimeOnly libs.junit.platform.launcher.iff
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'architecture-validator-spring-rules'
        }
    }
    repositories {
        maven {
            name = 'GitHubPackages'
            url = uri('https://maven.pkg.github.com/Arc-E-Tect/SoftwareEngineeringDoneRight-Code')
            credentials {
                username = System.getenv('GITHUB_ACTOR') ?: project.findProperty('gpr.user')
                password = System.getenv('GITHUB_TOKEN') ?: project.findProperty('gpr.key')
            }
        }
    }
}

test {
    useJUnitPlatform()
}