plugins {
    id 'java'
    id 'com.arc-e-tect.architecture-validator'
}

group = 'com.example.hybrid'
version = '0.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

architectureValidator {
    basePackage = 'com.example.hybrid'
    ignoreFailures = true
}