package com.arc_e_tect.gradle.architecture;

import com.arc_e_tect.sedr.utils.jacoco.marker.ExcludeFromJacocoGeneratedCodeCoverage;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * Reads the plugin version from the {@code architecture-validator.properties} classpath resource
 * that is generated by {@code processResources}.
 *
 * <p>The resource file is only present on the classpath when the plugin is resolved as a compiled
 * JAR (Gradle's {@code pluginUnderTestMetadata} mechanism makes it available to TestKit tests,
 * but not to ProjectBuilder-based unit tests). The entire class is therefore excluded from unit-test
 * coverage measurement and covered instead by the testComponent suite.</p>
 */
@ExcludeFromJacocoGeneratedCodeCoverage(
        justification = "Reads a classpath resource that is only present when the plugin is resolved as a compiled JAR."
                + " ProjectBuilder unit tests do not resolve the JAR, so neither the constructor nor"
                + " pluginVersion() can be reached. Covered by the testComponent suite.")
final class PluginMetadata {

    private static final String RESOURCE_NAME = "architecture-validator.properties";
    private static final String UNKNOWN_VERSION = "0.0.0";

    private PluginMetadata() {
    }

    static String pluginVersion() {
        Properties properties = new Properties();
        try (InputStream stream = PluginMetadata.class.getClassLoader().getResourceAsStream(RESOURCE_NAME)) {
            if (stream == null) {
                return UNKNOWN_VERSION;
            }
            properties.load(stream);
            return properties.getProperty("pluginVersion", UNKNOWN_VERSION);
        } catch (IOException ignored) {
            return UNKNOWN_VERSION;
        }
    }
}