plugins {
    id 'java'
    id 'com.arc-e-tect.architecture-validator'
}

group = 'com.arc-e-tect.example.vanilla'
version = '0.0.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

architectureValidator {
    basePackage = 'com.arc_e_tect.example.vanilla'
    ignoreFailures = true
    setJunitVersion(libs.versions.architecture.validator.junit.iff.get())
}