name: Example - JaCoCo Exclusion Report Build
on:
  push:
    paths:
      - 'examples/jacoco-exclusion-report/**/*.java'
      - 'examples/jacoco-exclusion-report/**/*.gradle'
      - 'examples/jacoco-exclusion-report/**/*.properties'
      - 'examples/jacoco-exclusion-report/**/libs.versions.toml'
      - '.github/workflows/example-jacoco-exclusion-report-build.yml'

jobs:
  Build-Example:
    name: Build Example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Build example
        run: |
          cd examples/jacoco-exclusion-report
          chmod +x ./gradlew
          ./gradlew build --no-daemon
