name: Example - Architecture Validator - Single Module Vanilla Build
on:
  push:
    paths:
      - 'examples/architecture-validator/single-module-vanilla/**/*.java'
      - 'examples/architecture-validator/single-module-vanilla/**/*.gradle'
      - 'examples/architecture-validator/single-module-vanilla/**/*.properties'
      - 'examples/architecture-validator/single-module-vanilla/**/libs.versions.toml'
      - '.github/workflows/example-architecture-validator-single-module-vanilla-build.yml'

jobs:
  Build-Example:
    name: Build Example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Build example
        run: |
          cd examples/architecture-validator/single-module-vanilla
          chmod +x ./gradlew
          ./gradlew build --no-daemon
